# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Darren Wong
url:              darrendub.com
paginate:         1
paginate_path:    "page:num"
baseurl:          ""
author:
  name:           Darren Wong
  description:    Interactive designer at Inkling. Connoisseur of Wes Anderson films and Drake lyrics.
  url:            darrendub.com
  email:          darrendavenwong@gmail.com

# Custom vars
repo:             https://github.com/darrendub/darrendub.github.io
markdown:         kramdown
highlighter:      rouge

# Style
## Set the Sass partials directory, as we're using @imports
#sass:
#  sass_dir: _scss
#  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate 


# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md